site_name: Pay with ConnectIPS
repo_url: https://github.com/codemanas/pay-with-connectips-docs
site_author: codemanas
theme:
  name: material
  font:
    text: Inclusive Sans
  logo: assets/logo.png
  palette:
    primary: custom
    accent: deep orange
extra_css:
  - stylesheets/extra.css
nav:
  - Installation: index.md
  - Getting Started: getting-started.md
  - Settings: settings.md